config/routes.rb
Rails.application.routes.draw do

  root "dashboard#index"

  resources :api_keys, only: [:create, :destroy]
  resources :events, only: [:index, :create]
  resources :importers, only: [:create, :index, :show, :destroy] do
    member do
      get 'run'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :streams, only: [:index, :show]

  get 'logout' => 'sessions#destroy'
  get 'settings' => 'settings#index'
  get 'system' => 'system#index'

end

app/models/stream.rb
class Stream < ActiveRecord::Base

  validates :name, presence: true, length: 5..32
  validates :slug, presence: true, length: 5..32

  has_many :events
  has_many :importers

  def to_param
    slug
  end

end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController

  def index
    @streams = Stream.all.order(id: :desc)
  end

  def show
    @stream = Stream.find_by(slug: params[:id].downcase)
  end

end

app/views/streams/index.html.haml
.container-fluid

  %table.table
    %thead
      %tr
        %th.text-left Name
        %th{width: 60}
        %th.text-center{width: 100} Events
    %tbody
      - @streams.each do |stream|
        %tr
          %td
            = link_to stream_path(stream) do
              = stream.name
          %td.text-center
            - if stream.importers.count > 0
              = link_to importers_path, class: 'text-success' do
                %span.fa.fa-fw.fa-cloud-download
                = stream.importers.size
          %td.text-center
            = link_to events_path(stream: stream) do
              = number_with_delimiter(stream.events.count)

app/views/streams/show.html.haml
.container-fluid

  %h2= @stream.name

  %table.table
    %thead
      %th Data
      %th.text-right{width: 100} Time
    %body
      - @stream.events.order(id: :desc).limit(25).each do |event|
        %tr
          %td
            %code= event.data
          %td.text-right
            = time_ago_in_words event.created_at