config/routes.rb
Rails.application.routes.draw do

  root "dashboard#index"

  resources :api_keys, only: [:create, :destroy]
  resources :events, only: [:index, :create]
  resources :importers, only: [:create, :index, :show, :destroy] do
    member do
      get 'run'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :streams, only: [:index, :show]

  get 'logout' => 'sessions#destroy'
  get 'settings' => 'settings#index'
  get 'system' => 'system#index'

end

app/models/importer.rb
class Importer < ActiveRecord::Base

  validates :endpoint, presence: true
  validates :provider, inclusion: { in: %w(logentries) }
  validates :schedule, numericality: { only_integer: true, greater_than_or_equal_to: 60 }
  validates :stream, presence: true

  belongs_to :stream

end

app/controllers/importers_controller.rb
class ImportersController < ApplicationController

  helper_method :schedule_periods

  def create
    @importer = Importer.new(params.require(:importer).permit(:stream_id, :provider, :endpoint, :schedule))
    if @importer.save
      flash[:success] = "Your importer has been registered"
    else
      flash[:error] = "Error: #{@importer.errors.full_messages.join(', ')}"
    end
    redirect_to importers_path
  end

  def index
    @importers = Importer.all.order(id: :desc)
  end

  def show
  end

  def destroy
    @importer = Importer.find(params[:id])
    @importer.destroy
    flash[:error] = "Your importer has been deleted"
    redirect_to importers_path
  end

  def run
    @importer = Importer.find(params[:id])
    if @importer.provider == 'logentries'
      Import::LogEntriesJob.perform_later(@importer)
    end
    flash[:success] = "Your import has been scheduled"
    redirect_to importers_path
  end

  private

  def schedule_periods
    {
      "Every minute" => 60,
      "Every 5 minutes" => 300,
      "Every 15 minutes" => 900,
      "Every 30 minutes" => 1800,
      "Every hour" => 3600,
      "Every 6 hours" => 21600,
      "Every day" => 86400,
      "Every 7 days" => 604800,
      "Every 30 days" => 2592000,
    }
  end

end

app/views/importers/index.html.haml
.container-fluid

  %br
  = form_for Importer.new do |f|

    .row
      .col-md-2
        = f.select :stream_id, options_from_collection_for_select(Stream.all, 'id', 'name', @stream.try(:slug)), { include_blank: '-- Stream --' }, class: 'form-control', required: true
      .col-md-2
        = f.select :provider, options_for_select("Log Entries" => "logentries"), { include_blank: '-- Provider --' }, class: 'form-control', required: true
      .col-md-5
        = f.text_field :endpoint, class: 'form-control', placeholder: 'Endpoint / URL', required: true
      .col-md-2
        = f.select :schedule, options_for_select(schedule_periods), {}, class: 'form-control'
      .col-md-1
        = f.button type: 'submit', class: 'btn btn-primary' do
          Create

  %br

  - if @importers.any?
    %table.table
      %thead
        %tr
          %th.text{width: 80} Provider
          %th.text-center{width: 200} Stream
          %th Endpoint
          %th{width: 150}
          %th{width: 60}
          %th{width: 10}
      %tbody
        - @importers.includes(:stream).each do |importer|
          %tr
            %td
              = importer.provider
            %td.text-center
              = link_to stream_path(importer.stream) do
                = importer.stream.name
            %td
              = text_field_tag :endpoint, importer.endpoint, class: 'form-control'
            %td
              - if importer.active?
                %span.text-success
                  %span.fa.fa-fw.fa-clock-o
                  Every #{time_ago_in_words(Time.now - importer.schedule).gsub('about ', '')}
              - else
                %span.text-muted
                  %span.fa.fa-fw.fa-pause
                  Every #{time_ago_in_words(Time.now - importer.schedule).gsub('about ', '')}
            %td
              = link_to run_importer_path(importer) do
                %span.fa.fa-fw.fa-terminal
                run
            %td
              = form_tag importer_path(importer), class: 'form-horizontal', method: 'delete' do
                = button_tag type: 'submit', class: 'btn btn-link btn-xs' do
                  %span.fa.fa-times.text-danger


  - else
    .text-center.text-muted
      %br
      %br
      No importers registered