config/routes.rb
Rails.application.routes.draw do

  root "dashboard#index"

  resources :api_keys, only: [:create, :destroy]
  resources :events, only: [:index, :create]
  resources :importers, only: [:create, :index, :show, :destroy] do
    member do
      get 'run'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :streams, only: [:index, :show]

  get 'logout' => 'sessions#destroy'
  get 'settings' => 'settings#index'
  get 'system' => 'system#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  helper_method :current_user

  def authenticate_api_key!
    key = params[:api_key] || request.headers['x-api-key']
    api_key = ApiKey.find_by(key: key)
    render json: { error: 'Invalid API Key Specified' }, status: 401 unless api_key.present?
  end

  def authenticate_user!
    if current_user.blank? && params[:controller] != 'sessions'
      flash[:error] = "You must sign in to do that"
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= begin
      if session[:user_id]
        user = User.find_by(id: session[:user_id])
        return nil unless user.present?
        session[:user_id]
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link(path = nil, options = nil, &block)
    li_options = current_page?(path) ? { class: "active" } : {}
    content_tag(:li, li_options) do
      link_to(path, options, &block)
    end
  end

end

app/views/application/_flash.html.haml
- [:error, :success, :info, :warning].each do |type|
  - if flash[type]
    .alert.alert-block{class: "alert-#{type.to_s.gsub('error', 'danger')}"}
      = flash[type]

app/views/application/_navbar.html.haml
.navbar.navbar-fixed-top.navbar-inverse
  .container-fluid
    = link_to root_path, class: 'navbar-brand' do
      Hoard
    %ul.nav.navbar-nav
      = nav_link streams_path do
        %span.fa.fa-fw.fa-database
        Streams
        (#{number_with_delimiter Stream.count})
      = nav_link events_path do
        %span.fa.fa-fw.fa-list
        Events
        (#{number_with_delimiter Event.count})
    %ul.nav.navbar-nav.navbar-right
      = nav_link importers_path do
        %span.fa.fa-fw.fa-cloud-download
      = nav_link system_path do
        %span.fa.fa-fw.fa-info
      = nav_link settings_path do
        %span.fa.fa-fw.fa-cogs
      = nav_link logout_path do
        %span.fa.fa-fw.fa-sign-out